# Time
CHECK_DB_TIME = 10000
# CHECK_DB_UPDATE_TIME = 60000
CHECK_DB_UPDATE_TIME = 600000

# count
AIR_LEAK_UNIT_COUNT = 4

PROCESS_NFC_ORDER_SENSOR = 0
PROCESS_NFC_ORDER_MIC = 1

ONE_BYTE_HEX = 0xFF
