DEFAULT_FONT_SIZE = 30

# touch
TOUCH_COMPORT_MAXIMUM_HEIGHT = 68
TOUCH_ORDER_MAXIMUM_HEIGHT = 72
TOUCH_DATA_MATRIX_MAXIMUM_HEIGHT = 130
TOUCH_MACHINE_MINIMUM_WIDTH = 500
TOUCH_STATUS_MAXIMUM_HEIGHT = 72

TOUCH_DATA_MATRIX_FONT_SIZE = 80
TOUCH_MACHINE_RESULT_FONT_SIZE = 120

# QR matching
NFC_FIXED_HEIGHT = 80
COMPORT_FIXED_HEIGHT = 80
MATCHING_PREVIOUS_PROCESS_MINIMUM_HEIGHT = 130
MATCHING_DATA_MATRIX_MINIMUM_WIDTH = 1000
MATCHING_STATUS_MAXIMUM_HEIGHT = 95

MATCHING_PREVIOUS_PROCESS_FONT_SIZE = 80
MATCHING_DATA_MATRIX_FONT_SIZE = 170
MATCHING_STATUS_FONT_SIZE = 50

# Air Leak
AIR_LEAK_UNIT_MINIMUM_WIDTH = 600
AIR_LEAK_RESULT_MINIMUM_HEIGHT = 500
AIR_LEAK_STATUS_FIXED_HEIGHT = 80

AIR_LEAK_RESULT_FONT_SIZE = 100
AIR_LEAK_UNIT_FONT_SIZE = 50

# MIC
MIC_PREVIOUS_CHECK_LABEL_FONT_SIZE = 50
MIC_PREVIOUS_CHECK_LABEL_CLEAN_TIME = 2000

# audio bus
AUDIO_BUS_NFC_FIXED_HEIGHT = 50
AUDIO_BUS_NFC_FONT_SIZE = 13
AUDIO_BUS_PREVIOUS_PROCESS_FIXED_HEIGHT = 80
AUDIO_BUS_LABEL_MINIMUM_WIDTH = 600

# audio bus config
AUDIO_BUS_PATH_LINE_EDIT_MIN_WIDTH = 450
AUDIO_BUS_CONFIG_GRADE_EDIT_FIXED_WIDTH = 100
AUDIO_BUS_CONFIG_BUTTON_MIN_WIDTH = 150

AUDIO_BUS_PATH_LINE_EDIT_FONT_SIZE = 17
AUDIO_BUS_GRADE_LINE_EDIT_FONT_SIZE = 20

# sensor
SENSOR_CHANNEL_GROUP_MINIMUM_WIDTH = 310
SENSOR_RESULT_FIXED_HEIGHT = 350

SENSOR_PREVIOUS_PROCESS_FONT_SIZE = 80
SENSOR_RESULT_FONT_SIZE = 100

# release
RELEASE_LABEL_MINIMUM_WIDTH = 700
RELEASE_DATA_MATRIX_FIXED_HEIGHT = 100
RELEASE_RESULT_MIN_HEIGHT = 400

RELEASE_RESULT_FONT_SIZE = 60
RELEASE_GRADE_FONT_SIZE = 250
RELEASE_STATUS_FONT_SIZE = 35

# order
ORDER_SEARCH_BOX_MINIMUM_WIDTH = 380