# simple string upper

STR_MACHINE_COMPORT = "MACHINE COMPORT"
STR_ORDER_NUMBER = "ORDER NUMBER"
STR_DATA_MATRIX = "DATA MATRIX"
STR_MACHINE_RESULT = "MACHINE RESULT"
STR_STATUS = "STATUS"

STR_TOUCH_PROCESS = "TOUCH PROCESS"

STR_PREVIOUS_PROCESS = "PREVIOUS PROCESS"
STR_QR_MATCHING = "QR MATCHING"

STR_NFC = "NFC"

STR_READY_TO_QR_SCAN = "READY TO QR SCAN!!"
